language:
  - cpp

os:
  - linux  # shipping linux

env:
  global:
    - PYTHON_VERSION=3.6

before_install:
  - git clone https://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - conda install -c conda-forge cmake
  - conda install -c massich matio-cmake

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_PREFIX_PATH=/home/travis/miniconda/envs/test/lib/cmake/
  - cmake --build . -- -j 2
  - ldd hello
  - ./hello

notifications:
  email: false
